# Generated by Django 5.1.1 on 2024-10-02 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('participants', models.PositiveIntegerField()),
                ('required_fund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acquired_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fund_pps', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='auth.group')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='auth.group')),
                ('manager_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_1', to=settings.AUTH_USER_MODEL)),
                ('manager_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
