# Generated by Django 5.1.1 on 2024-10-03 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='event',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='event',
            name='branch',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='fund_pps',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='manager_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='batch',
            field=models.ManyToManyField(limit_choices_to={'name__regex': '^\\d{2}$'}, related_name='batch', to='auth.group'),
        ),
        migrations.AddField(
            model_name='event',
            name='branch',
            field=models.ManyToManyField(limit_choices_to={'name__regex': '^[a-zA-Z]{2}$'}, related_name='branch', to='auth.group'),
        ),
    ]
